Traceback (most recent call last):
  File "mineSweeper.py", line 18, in <module>
pygame.error: Couldn't open textures//mine.png
